Repository AI4quantum/maestro, pull requests merged in 2025-03, with the labels that each got.

#293 proposed schema for cron job events
  maestro/schemas/workflow_schema.json
  maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml
  maestro/tests/yamls/workflows/simple_cron_workflow.yaml
Labels: enhancement, feature

#299 fixes issue #298
  maestro/cli/commands.py
Labels: bug

#296 first version of Workflow::to_mermaid method
  maestro/src/mermaid.py
  maestro/src/workflow.py
  maestro/tests/workflow/test_mermaid.py
  maestro/tests/yamls/workflows/simple_workflow.yaml
Labels: enhancement

#310 implements CLI mermaid command
  maestro/cli/commands.py
  maestro/cli/maestro.py
  maestro/src/mermaid.py
  maestro/src/workflow.py
  maestro/tests/cli/test_commands.py
  maestro/tests/workflow/test_mermaid.py
Labels: enhancement

#321 CI workflow / job to run maestro mermaid command on all existing workflows
  .github/workflows/maestro_check-mermaid.yaml
  maestro/tools/check-mermaid.sh
Labels: enhancement

#328 fixes issue #327
  .github/workflows/maestro_check-schemas.yaml
  maestro/cli/commands.py
  maestro/cli/maestro.py
  maestro/tests/cli/test_commands.py
Labels: enhancement

#324 instructions for deployment
  maestro/README.md
Labels: documentation

#316 feature: add support for condition (case/do/default and if/then/else)
  maestro/src/mermaid.py
  maestro/tests/workflow/test_mermaid.py
  maestro/tests/yamls/workflows/conditional_case_workflow.yaml
  maestro/tests/yamls/workflows/conditional_if_workflow.yaml
  maestro/tests/yamls/workflows/funnier_workflow.yaml
  maestro/tools/run-all.sh
Labels: enhancement

#333 feature: add global exception to Mermaid generation
  maestro/schemas/workflow_schema.json
  maestro/src/mermaid.py
  maestro/tests/workflow/test_mermaid.py
  maestro/tests/yamls/workflows/conditional_case_workflow.yaml
  maestro/tests/yamls/workflows/conditional_if_workflow.yaml
  maestro/tests/yamls/workflows/conditional_workflow.yaml
  maestro/tests/yamls/workflows/input_workflow.yaml
  maestro/tests/yamls/workflows/parallel_workflow.yaml
  maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml
  maestro/tests/yamls/workflows/simple_cron_workflow.yaml
  maestro/tests/yamls/workflows/simple_workflow.yaml
Labels: enhancement, feature

#335 feature: adds mermaid for workflow events (cron)
  maestro/schemas/workflow_schema.json
  maestro/src/mermaid.py
  maestro/tests/workflow/test_mermaid.py
  maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml
  maestro/tests/yamls/workflows/simple_cron_workflow.yaml
Labels: enhancement, feature

#340 fixes issue #339
  maestro/src/agents/bee_agent.py
  maestro/src/agents/crewai_agent.py
  maestro/src/agents/mock_agent.py
Labels: enhancement

#338 fixes issues #337
  maestro/src/agents/mock_agent.py
Labels: enhancement

#342 fixed newline error
  maestro/deployments/api.py
Labels: bug

#343 feature: adds parallel sequenceDiagram
  maestro/src/mermaid.py
  maestro/tests/workflow/test_mermaid.py
Labels: enhancement, feature

#346 feature: Issue #297 loop sequenceDiagram
  maestro/src/mermaid.py
  maestro/tests/workflow/test_mermaid.py
Labels: enhancement

#347 fixing default prompt issue
  maestro/cli/commands.py
  maestro/cli/maestro.py
  maestro/deployments/api.py
  maestro/tests/cli/test_commands.py
Labels: enhancement

#351 Agent renaming
  maestro/demos/workflows/meta-agents/weather/agent/workflow.yaml
  maestro/demos/workflows/meta-agents/weather/output/agents.yaml
  maestro/demos/workflows/meta-agents/weather/output/workflow.yaml
  maestro/demos/workflows/meta-agents/weather/workflow/workflow.yaml
  maestro/demos/workflows/weather-checker.ai/agents.yaml
  maestro/demos/workflows/weather-checker.ai/workflow.yaml
Labels: enhancement

#361 prompt updates
  maestro/demos/workflows/activity-planner.ai/agents.yaml
  maestro/demos/workflows/activity-planner.ai/workflow.yaml
Labels: bug

#371 Bug: using json serialization instead of fstrings to prevent newline errors
  maestro/src/agents/bee_agent.py
Labels: bug

#355 added instructions to funnier_agents.yaml
  maestro/tests/yamls/agents/funnier_agents.yaml
  maestro/tests/yamls/workflows/funnier_workflow.yaml
Labels: bug

#348 fixes issue #325 to use new BeeAI naming
  maestro/README.md
  maestro/demos/CONTRIBUTING.md
  maestro/demos/workflows/activity-planner.ai/workflow.md
  maestro/src/__init__.py
  maestro/src/agents/agent_factory.py
  maestro/src/agents/beeai_agent.py
  maestro/src/agents/mock_agent.py
  maestro/src/workflow.py
  maestro/tests/bee/test_bee.py
Labels: enhancement

#376 make streamlit the default deployment mode
  maestro/README.md
  maestro/cli/commands.py
  maestro/cli/maestro.py
Labels: enhancement
