Repository AI4quantum/maestro, pull requests merged in 2025-06, with the labels that each got.

#486 demo: cbom.ai
  .github/workflows/maestro_demo-tests.yaml
  demos/workflows/cbom.ai/README.md
  demos/workflows/cbom.ai/agents.yaml
  demos/workflows/cbom.ai/workflow.yaml
  demos/workflows/mcp-gh-tools.ai/README.md
  schemas/workflow_schema.json
  src/agents/agent_factory.py
  src/agents/custom_agent.py
  src/agents/metrics_agent.py
  src/agents/prompt_agent.py
  src/agents/scoring_agent.py
  src/mermaid.py
  src/step.py
  src/workflow.py
  tests/agents/test_metrics_agent.py
  tests/agents/test_prompt_agent.py
  tests/agents/test_scoring_agent.py
  tests/yamls/agents/prompt_agent.yaml
  tests/yamls/agents/scoring_agent.yaml
  tests/yamls/workflows/metric_workflow.yaml
  tests/yamls/workflows/prompt_agent.yaml
  tests/yamls/workflows/scoring_workflow.yaml
Labels: demo

#508 demo: Cbom w codeagent
  demos/workflows/cbom.ai/README.md
  demos/workflows/cbom.ai/agents.yaml
  demos/workflows/cbom.ai/example-cbom.json
  demos/workflows/cbom.ai/workflow.yaml
Labels: demo

#522 bug: values of metadata.labels must be sanitized
  cli/commands.py
  demos/workflows/weather-checker.ai/agents.yaml
Labels: bug

#516 feature: add quantum portfolio optimizer workflow
  demos/workflows/portfolio/README.md
  demos/workflows/portfolio/agent.yaml
  demos/workflows/portfolio/workflow.yaml
Labels: demo

#519 demo: Qaoa workflow
  demos/workflows/qaoa/README.md
  demos/workflows/qaoa/agents.yaml
  demos/workflows/qaoa/functions/qaoa/__init__.py
  demos/workflows/qaoa/functions/qaoa/qaoa.py
  demos/workflows/qaoa/scripts/upload_function.py
  demos/workflows/qaoa/workflow.yaml
Labels: demo

#539 chore: switching licenses to SPDX-syle
  demos/agents/crewai/activity_planner/activity_planner.py
  demos/agents/crewai/activity_planner/inspect_agent.py
  demos/agents/crewai/generic/generic_agent.py
  demos/workflows/activity-planner.ai/src/run.py
  demos/workflows/qaoa/functions/qaoa/qaoa.py
  demos/workflows/qaoa/scripts/upload_function.py
  deployments/api.py
  operator/api.py
  src/maestro/__init__.py
  src/maestro/cli/__init__.py
  src/maestro/cli/commands.py
  src/maestro/cli/common.py
  src/maestro/cli/maestro.py
  src/maestro/cli/streamlit_deploy.py
  src/maestro/deploy.py
  src/maestro/mermaid.py
  src/maestro/workflow.py
  src/workflow.py
  tests/__init__.py
  tests/agents/beeai_agent/test_beeai.py
  tests/agents/crewai_agent/test_crewai.py
  tests/agents/openai_agent/test_openai.py
  tests/agents/test_agent.py
  tests/agents/test_agent_factory.py
  tests/cli/test_commands.py
  tests/examples/test_condition.py
  tests/examples/test_parallel.py
  tests/integration/deploys/test_deploy.py
  tests/integration/dry_run/test_dry_run.py
  tests/workflow/test_code.py
  tests/workflow/test_cron.py
  tests/workflow/test_exception.py
  tests/workflow/test_inputs.py
  tests/workflow/test_loop.py
  tests/workflow/test_mermaid.py
  tests/workflow/test_parallel.py
  tools/scripts.py
Labels: chore

#538 demo: add result plot step for portfolio
  demos/workflows/portfolio/README.md
  demos/workflows/portfolio/agents.yaml
  demos/workflows/portfolio/workflow.yaml
Labels: enhancement

#544 bug: skip slack agent
  tools/run-demos.sh
Labels: bug

#551 bug: fixes for qaoa demo
  demos/workflows/qaoa/README.md
  demos/workflows/qaoa/agents.yaml
Labels: bug

#543 feature: add some qiskit MCP tools
  mcp/README.md
  mcp/examples/mcp_qiskit.py
  mcp/mcptools/qiskit_mcp.py
  mcp/tests/test_mcp_tools.py
  requirements.txt
Labels: enhancement, feature

#554 bug: fix save_agent
  src/maestro/agents/agent.py
  src/maestro/workflow.py
  tests/agents/test_save_restore.py
  tests/yamls/agents/beeai_agent.yaml
  tests/yamls/agents/openai_agent.yaml
Labels: bug

#541 feature: support pip installing maestro
  .github/release.yml
  .github/workflows/maestro_check-mermaid.yaml
  .github/workflows/maestro_check-schemas.yaml
  .github/workflows/maestro_demo-tests.yaml
  .github/workflows/maestro_deploy-tests.yaml
  .github/workflows/maestro_operator-build.yaml
  .github/workflows/maestro_operator-test.yaml
  .github/workflows/maestro_release.yaml
  .github/workflows/maestro_run-tests.yaml
  .github/workflows/maestro_test-workflow.yaml
  CONTRIBUTING.md
  README.md
  demos/CONTRIBUTING.md
  demos/example.env
  demos/workflows/activity-planner-crewai.ai/README.md
  demos/workflows/activity-planner.ai/README.md
  demos/workflows/activity-planner.ai/setup.sh
  demos/workflows/cbom.ai/README.md
  demos/workflows/ibm-summary.ai/README.md
  demos/workflows/ibm-summary.ai/example.env
  demos/workflows/ibm-summary.ai/run.sh
  demos/workflows/ibm-summary.ai/workflow.yaml
  demos/workflows/openai-mcp.ai/README.md
  demos/workflows/portfolio/README.md
  demos/workflows/qaoa/README.md
  demos/workflows/simple/README.md
  demos/workflows/simple/agents.yaml
  demos/workflows/simple/workflow.yaml
  demos/workflows/summary.ai/README.md
  demos/workflows/summary.ai/workflow.yaml
  demos/workflows/weather-checker.ai/README.md
  demos/workflows/weather-checker.ai/example.env
  example.env
  maestro
  pyproject.toml
  requirements-extra.txt
  requirements.txt
  src/maestro/__init__.py
  src/maestro/cli/run_maestro.py
  src/maestro/cli/streamlit_deploy.py
  src/maestro/cli/streamlit_meta_agents_deploy.py
  src/maestro/images/maestro-gemini.png
  src/maestro/images/maestro-gemini2.png
  src/maestro/images/maestro.png
  tools/run-meta-agent.sh
  tools/setup_maestro.sh
Labels: test, feature
