Repository AI4quantum/maestro, pull requests merged in 2025-07, with the labels that each got.

#557 feature: serve agent
  docs/USER_GUIDE.md
  pyproject.toml
  src/maestro/cli/commands.py
  src/maestro/cli/fastapi_serve.py
  src/maestro/cli/run_maestro.py
  tests/integration/serve/test_serve_integration.py
  tests/yamls/agents/serve_test_agent.yaml
Labels: feature

#575 chore: list of maestro release names
  .release_names.md
Labels: chore

#583 feature: add some beeai tool yamls
  tests/yamls/tools/duckduckgo_tools.yaml
  tests/yamls/tools/openmeteo_tools.yaml
  tests/yamls/tools/python_tools.yaml
  tests/yamls/tools/simple_tools.yaml
  tests/yamls/tools/wikipedia_tools.py
Labels: enhancement, feature

#574 fix: allow cors for maestro serve
  src/maestro/agents/openai_agent.py
  src/maestro/cli/fastapi_serve.py
Labels: bug

#591 enhancment: auto update releases names
  .github/workflows/maestro_release.yaml
  api/manual_test_api.py
  tools/get_release_name.py
Labels: enhancement

#594 chore: switch to `uv sync` for dev install
  .github/workflows/maestro_check-mermaid.yaml
  .github/workflows/maestro_check-schemas.yaml
  .github/workflows/maestro_demo-tests.yaml
  .github/workflows/maestro_deploy-tests.yaml
  .github/workflows/maestro_operator-build.yaml
  .github/workflows/maestro_operator-test.yaml
  .github/workflows/maestro_release.yaml
  .github/workflows/maestro_run-tests.yaml
  CONTRIBUTING.md
  README.md
  demos/CONTRIBUTING.md
  demos/agents/crewai/activity_planner/README.md
  demos/workflows/activity-planner-crewai.ai/README.md
  demos/workflows/common/doctor.sh
  pyproject.toml
  src/maestro/agents/meta_agent/doctor.sh
  tools/run-demos.sh
Labels: chore

#597 chore: update release_names.md to match name
  .release_names.md
Labels: chore

#598 feature: DSPy Agent
  operator/Dockerfile-engine
  operator/entrypoint_api.sh
  pyproject.toml
  src/maestro/agents/agent.py
  src/maestro/agents/agent_factory.py
  src/maestro/agents/dspy_agent.py
  tests/workflow/test_dspy_agent.py
  tests/yamls/agents/dspy_agent.yaml
  tests/yamls/workflows/dspy_workflow.yaml
Labels: feature

#602 demo: make qchem ai public and add readme
  demos/workflows/qchem.ai/README.md
  demos/workflows/qchem.ai/agents.yaml
  demos/workflows/qchem.ai/example.env
  demos/workflows/qchem.ai/requirements.txt
  demos/workflows/qchem.ai/workflow.yaml
Labels: demo

#618 chore: correct crewai dependency warning message
  src/maestro/agents/crewai_agent.py
Labels: chore

#617 bug: fixes issue #616
  .gitignore
  tools/check-mermaid.sh
  tools/check-schemas.sh
Labels: bug

#610 enhancement: add maestro Dockerfiles
  .github/workflows/maestro_build_upload_images.yaml
  CONTRIBUTING.md
  Dockerfile
  Dockerfile-cli
  tools/buildimg.sh
Labels: enhancement

#634 chore: cleanup ci after demo move
  .github/workflows/maestro_operator-test.yaml
  .github/workflows/maestro_release.yaml
  .github/workflows/maestro_test-workflow.yaml
Labels: chore

#636 enhancement: make request data and response object configurable in RemoteAgent
  src/maestro/agents/remote_agent.py
Labels: enhancement

#643 bug: set correct CI perms for releases
  .github/workflows/maestro_build_upload_images.yaml
  .github/workflows/maestro_release.yaml
  Dockerfile
  pyproject.toml
Labels: bug

#663 project license as a toml table is deprecated
  pyproject.toml
Labels: chore

#664 feat: enable llm url override via yaml spec
  src/maestro/agents/beeai_agent.py
  src/maestro/agents/openai_agent.py
  tests/yamls/agents/simple_local_agent.yaml
Labels: enhancement

#667 enhancement/bug: allow validate to be accessible outside of repo
  pyproject.toml
  src/maestro/cli/commands.py
  src/maestro/schemas/agent_schema.json
  src/maestro/schemas/tool_schema.json
  src/maestro/schemas/tool_toolhive_schema_full.json
  src/maestro/schemas/workflow_schema.json
  tests/cli/test_commands.py
  tests/integration/dry_run/test_dry_run.py
Labels: bug, enhancement

#676 test: improve test output in CI
  .github/workflows/maestro_run-tests.yaml
  src/maestro/deploy.py
  tests/cli/test_commands.py
Labels: bug, test
