Repository AI4quantum/maestro, pull requests merged in 2025-04, with the labels that each got.

#380 feature: first version of meta-agents streamlit UI/UX
  maestro/cli/commands.py
  maestro/cli/maestro.py
  maestro/cli/streamlit_deploy.py
  maestro/cli/streamlit_meta_agents_deploy.py
  maestro/cli/streamlit_workflow_ui.py
  maestro/src/workflow.py
  maestro/tests/cli/test_commands.py
  maestro/tests/meta_agents/simple_prompt.txt
Labels: enhancement, feature

#381 meta agent src updates, prompt and readme updates
  maestro/README.md
  maestro/demos/workflows/meta-agents/activity-planner.ai/agents/agents.yaml
  maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/agents.yaml
  maestro/src/agents/meta_agent/agents.yaml
  maestro/src/agents/meta_agent/test.sh
  maestro/src/agents/meta_agent/workflow_agent.yaml
  maestro/src/agents/meta_agent/workflow_workflow.yaml
  maestro/tools/run-demos.sh
Labels: enhancement

#388 Bug: workflow deployment not rendering
  maestro/cli/streamlit_meta_agents_deploy.py
  maestro/src/agents/meta_agent/agents.yaml
Labels: bug

#389 Fix streaming output
  maestro/cli/streamlit_deploy.py
Labels: bug

#392 Add streaming output to meta agent UI
  maestro/cli/streamlit_workflow_ui.py
Labels: enhancement

#399 test agents refactoring
  maestro/cli/streamlit_workflow_ui.py
  maestro/src/agents/agent.py
  maestro/src/agents/openai_agent.py
  maestro/tests/agents/beeai/__init__.py
  maestro/tests/agents/beeai/agents.yaml
  maestro/tests/agents/beeai/test_bee.py
  maestro/tests/agents/beeai/workflow.yaml
  maestro/tests/agents/crewai/__init__.py
  maestro/tests/agents/crewai/agents.yaml
  maestro/tests/agents/crewai/crew_dummy.py
  maestro/tests/agents/crewai/test_crewai.py
  maestro/tests/agents/crewai/workflow.yaml
  maestro/tests/agents/meta_agents/simple_prompt.txt
  maestro/tests/agents/meta_agents/weather_prompt.txt
  maestro/tests/cli/test_commands.py
Labels: bug, enhancement

#404 Add parsers
  maestro/demos/workflows/meta-agents/activity-planner.ai/agents/agents.yaml
  maestro/demos/workflows/meta-agents/activity-planner.ai/agents/workflow.yaml
  maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/agents.yaml
  maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/workflow.yaml
  maestro/src/agents/meta_agent/agents.yaml
  maestro/src/agents/meta_agent/workflow_agent.yaml
  maestro/src/agents/meta_agent/workflow_workflow.yaml
Labels: bug, enhancement

#403 feature: load and create generated <agents/workflow>.yaml files
  maestro/cli/streamlit_meta_agents_deploy.py
  maestro/cli/streamlit_workflow_ui.py
Labels: enhancement

#406 add mermaid diagrams to each demo
  .github/workflows/maestro_check-schemas.yaml
  maestro/demos/workflows/activity-planner-crewai.ai/README.md
  maestro/demos/workflows/activity-planner.ai/README.md
  maestro/demos/workflows/meta-agents/README.md
  maestro/demos/workflows/summary.ai/README.md
  maestro/demos/workflows/weather-checker.ai/README.md
  maestro/src/agents/meta_agent/README.md
  maestro/tools/update_readme.sh
Labels: enhancement

#409 Update summaryai
  maestro/demos/workflows/summary.ai/old_yamls/agent_store.json
  maestro/demos/workflows/summary.ai/old_yamls/agents.yaml
  maestro/demos/workflows/summary.ai/old_yamls/workflow.yaml
  maestro/demos/workflows/summary.ai/workflow.yaml
Labels: enhancement

#412 feature: OpenAIAgent support
  maestro/pyproject.toml
  maestro/src/__init__.py
  maestro/src/agents/agent.py
  maestro/src/agents/agent_factory.py
  maestro/src/agents/beeai_agent.py
  maestro/src/agents/openai_agent.py
  maestro/src/workflow.py
  maestro/tests/agents/beeai_agent/__init__.py
  maestro/tests/agents/beeai_agent/agents.yaml
  maestro/tests/agents/beeai_agent/test_beeai.py
  maestro/tests/agents/beeai_agent/workflow.yaml
  maestro/tests/agents/crewai_agent/__init__.py
  maestro/tests/agents/crewai_agent/agents.yaml
  maestro/tests/agents/crewai_agent/crew_dummy.py
  maestro/tests/agents/crewai_agent/test_crewai.py
  maestro/tests/agents/crewai_agent/workflow.yaml
  maestro/tests/agents/openai_agent/__init__.py
  maestro/tests/agents/openai_agent/agents.yaml
  maestro/tests/agents/openai_agent/test_openai.py
  maestro/tests/agents/openai_agent/workflow.yaml
  maestro/tests/agents/test_agent_factory.py
Labels: enhancement, feature

#416 updating summary agents
  maestro/demos/workflows/summary.ai/README.md
  maestro/demos/workflows/summary.ai/agents.yaml
  maestro/demos/workflows/summary.ai/workflow.yaml
Labels: enhancement

#421 demo/enhancement: Update summary arxiv agent
  maestro/demos/workflows/summary.ai/agents.yaml
  maestro/demos/workflows/summary.ai/workflow.yaml
Labels: demo

#423 demo: update agents defs
  maestro/demos/workflows/summary.ai/agents.yaml
Labels: demo

#429 feature: fixes issue #350
  maestro/cli/commands.py
  maestro/cli/maestro.py
  maestro/demos/agents/crewai/activity_planner/config/config.yaml
  maestro/tests/cli/test_commands.py
  maestro/tools/check-schemas.sh
Labels: enhancement

#430 fixes issue #306 by adding --prompt to run command
  maestro/cli/commands.py
  maestro/cli/common.py
  maestro/cli/maestro.py
  maestro/tests/cli/test_commands.py
Labels: feature

#433 enhancement: prompt adjustment
  maestro/demos/workflows/weather-checker.ai/agents.yaml
Labels: enhancement

#428 Add multiple type agent test
  maestro/demos/agents/crewai/activity_planner/config/agents.yaml
  maestro/demos/agents/crewai/generic/__init__.py
  maestro/demos/agents/crewai/generic/config/agents.yaml
  maestro/demos/agents/crewai/generic/config/tasks.yaml
  maestro/demos/agents/crewai/generic/generic_agent.py
  maestro/src/agents/crewai_agent.py
  maestro/tests/yamls/agents/multi_agents.yaml
  maestro/tests/yamls/agents/multi_agents_crew2.yaml
  maestro/tests/yamls/workflows/multi_workflow.yaml
  maestro/tools/check-schemas.sh
Labels: enhancement

#434 litellm dependency conflict issue workaround
  .github/workflows/maestro_check-mermaid.yaml
  .github/workflows/maestro_check-schemas.yaml
  .github/workflows/maestro_demo-tests.yaml
  .github/workflows/maestro_deploy-tests.yaml
  .github/workflows/maestro_run-tests.yaml
  maestro/pyproject.toml
  maestro/src/agents/crewai_agent.py
  maestro/tests/agents/crewai_agent/test_crewai.py
Labels: enhancement

#438 feature: add the cron job event support
  maestro/pyproject.toml
  maestro/src/workflow.py
  maestro/tests/workflow/test_mermaid.py
  maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml
  maestro/tests/yamls/workflows/simple_cron_workflow.yaml
Labels: enhancement, feature

#451 enhancement: summary.ai cron job
  maestro/demos/workflows/summary.ai/agents.yaml
  maestro/demos/workflows/summary.ai/workflow.yaml
  maestro/demos/workflows/weather-checker.ai/README.md
  maestro/src/mermaid.py
  requirements.txt
Labels: demo

#457 demo: new summary demo to align w/clients needs
  maestro/demos/README.md
  maestro/demos/workflows/summary.ai/README.md
  maestro/demos/workflows/summary.ai/agents.yaml
  maestro/demos/workflows/summary.ai/workflow.yaml
Labels: documentation, enhancement, demo
