Repository AI4quantum/maestro, pull requests merged in 2025-08, with the labels that each got.

#681 feature: enable workflow streaming in api
  README.md
  src/maestro/cli/fastapi_serve.py
  src/maestro/workflow.py
  tests/integration/serve/test_streaming.py
Labels: enhancement

#660 chore: Agent MCP tool support utilities
  .github/workflows/maestro_mcp_tool_test.yaml
  docs/USER_GUIDE.md
  operator/Dockerfile-engine
  src/maestro/agents/beeai_agent.py
  src/maestro/agents/dspy_agent.py
  src/maestro/agents/openai_agent.py
  src/maestro/agents/openai_mcp.py
  src/maestro/tool_utils.py
  tests/utils/responses.yml
  tests/yamls/agents/beeai_mcp_agent.yaml
  tests/yamls/agents/openai_mcp_agent.yaml
  tests/yamls/workflows/beeai_mcp_workflow.yaml
  tests/yamls/workflows/openai_mcp_workflow.yaml
Labels: chore

#671 feat: support url or file path for code or instructions
  docs/USER_GUIDE.md
  src/maestro/agents/agent.py
  src/maestro/agents/utils.py
  src/maestro/cli/common.py
  tests/agents/test_utils.py
  uv.lock
Labels: enhancement

#685 fix: maestro-cli docker image was mistagged
  .github/workflows/maestro_build_upload_images.yaml
Labels: bug

#708 feat: local mcp server registration
  docs/USER_GUIDE.md
  src/maestro/mcptool.py
  src/maestro/tool_utils.py
  tests/test_tool_utils.py
Labels: enhancement
