Repository AI4quantum/maestro, pull requests merged in 2025-05, with the labels that each got.

#468 update maintainers
  MAINTAINERS.md
Labels: enhancement

#470 enhancement: added nlp agent for summary
  demos/workflows/summary.ai/README.md
  demos/workflows/summary.ai/agents.yaml
  demos/workflows/summary.ai/workflow.yaml
Labels: demo

#475 bug: Fix dependency installing warning
  .gitignore
  README.md
  requirements.txt
  tools/setup_maestro.sh
Labels: bug

#477 remove old .env.example and add new images
  .env.example
  images/maestro-gemini.png
  images/maestro-gemini2.png
Labels: documentation, enhancement

#479 enhancement: update actions file w setup
  .github/workflows/maestro_demo-tests.yaml
  .github/workflows/maestro_run-tests.yaml
Labels: enhancement
